### ISSUE TITLE
Bug report - Unhandled Exception Error

### ISSUE THREAD

**Issue by B1uesh1ft** [Anything144/Advanced-Kea#1]
**Describe the bug**
Unhandled Exception Error

**To Reproduce**
Run Advanced Kea, it's happening almost every time I run it now.

**Kea Version**
Most recent.

Output:

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at Kea.Main.<GetChapterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kea.Main.<DownloadQueueAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kea.Main.<startBtn_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by TheEclipseMaster** [comment]
Same issue here

**Comment by corruleum** [comment]
Same issue here. It seems to happen whenever a comic has more than 100 entries/10 pages of archive.

I have also noticed that, prior to it throwing an error, it scans pages 2 through 10 (or other pages, in some cases) fairly quickly and then remains on page 10 (or a later one) for a period of time before erroring; on a successful download, page scans take longer but it successfully makes it to page 11 and beyond.

I do not know what causes this difference, I only know that it can take a few dozen attempts before it successfully downloads, using the exact same settings each time.

**Comment by B1uesh1ft** [comment]
This is my experience as well. It gets hung up scanning a page, and then crashes. If it actually starts downloading, it's usually fine, but it crashes during scanning.

**Comment by VRArt1** [comment]
Also having this issue.

**Comment by MegrezPines** [comment]
Today it's Nov 17, 24. I've also had this issue ever since successfully downloading one whole webtoon series on Nov 3, without the last chapter. Kea was scooping through over 10 pages and downloading everything like a pro.
But ever since the last chapter was released on Nov 9, I just couldn't download that last chapter or the whole series or any series anymore. It just kept giving me 429 ever since. 
Would that error be caused by Webtoon taking preventative measures when a series ended? Or was it simply them closing limit rate the server periodically during peak season (when people are freer in the Winter and start reading more comics)?

**Comment by MegrezPines** [comment]
UPDATE! I SUDDENLY FOUND A SOLUTION!
Today is Nov 24, 24. I recalled back on Nov 3, when I used Kea to download (almost) the whole series, at that time, I was using a VPN, connecting to an Asian country. So I used Mullvad to connect back to Singapore, and it worked! No 429 whatsoever. I also tested with Indonesia, Thailand, Turkey, Israel, Cyprus, and Hong Kong, and all of them worked flawlessly. 

I'm not sure what is the rules behind this. Is the traffic of those countries less than average so Webtoon doesn't bother to rate-limit them? I tried to connect to Japan, it's the only Asian country that has a Mullvad server and it is also rate-limited by Webtoons, which I received a 429 immediately.

Well, I'm pretty confident that if you got a 429 when downloading, no matter what VPN you eventually choose to use, just hop on another country and most likely the download would go smoothly. I can only test the Asian servers provided by Mullvad (yes, Mullvad only has connections to 8 Asian countries), so it's not a comprehensive list, but I'm sure there are more countries that you can connect to that won't give you a 429 error. Whoever reads this in the future, you're welcome!

P/s: if you want to archive both the PDF and "multiple image" versions of the same comics into the same folder, my advice is to download the PDFs first and the images later. 
Why? Because the naming scheme for the PDF files is the same for the image folders.
If the save location is the same, and the image folders were created first, then when the PDFs got downloaded with the same name, it would override the images folder! 
However, if you download the PDF first and then download the multiple images later, this time when the folders are created, they don't override the PDF files with the same name.
Weird, right? 

Alright, have fun downloading!
